/**
 * Boat domain types.
 *
 * Maps to SRS FR-021 (multiple profiles), FR-022 (seed DB), FR-023
 * (editable specs), FR-024 (custom boat), FR-025 (fuel range).
 *
 * Storage units (imperial + nautical) match the conventional US
 * recreational-boating vernacular. UI converts to user preference.
 */

export type Category =
  | 'center-console'
  | 'cruiser'
  | 'bowrider'
  | 'pontoon'
  | 'sailboat'
  | 'trawler'
  | 'jet'
  | 'other';

export type EngineType = 'outboard' | 'sterndrive' | 'inboard' | 'jet' | 'sail-aux';

export type FuelType = 'gasoline' | 'diesel' | 'electric';

/**
 * A canonical, immutable seed-database entry. These ship with the app
 * and are read-only. Users derive their own BoatProfile from one of
 * these (or create a profile from scratch).
 */
export interface BoatSeed {
  /** Stable slug: `<manufacturer>-<model>` lowercased and hyphenated. */
  id: string;
  manufacturer: string;
  model: string;
  category: Category;

  /** Length overall, feet. */
  loaFt: number;
  /** Beam at widest point, feet. */
  beamFt: number;
  /** Draft at design displacement, feet. */
  draftFt: number;
  /** Dry / typical operating displacement, pounds. */
  displacementLbs: number;

  engineType: EngineType;
  /** Total propulsion horsepower across all engines. */
  totalHp: number;

  /** Comfortable cruise SOG (smooth water), knots. */
  cruiseSpeedKn: number;
  /** Wide-open-throttle SOG (smooth water), knots. */
  maxSpeedKn: number;

  /** Total usable fuel capacity, US gallons. */
  fuelCapacityGal: number;
  /** Fuel burn at cruise speed, US gallons per hour. */
  fuelBurnGph: number;
  fuelType: FuelType;
}

/**
 * The user-owned record. Includes everything a seed has, plus identity,
 * provenance, mutable user fields, and timestamps.
 *
 * The shape extends BoatSeed because the user is free to override any
 * factory value — even ones that came from the seed.
 */
export interface BoatProfile extends BoatSeed {
  /** UUID generated by `crypto.randomUUID()` at creation. */
  uuid: string;
  /** Where the record came from — useful for "reset to seed" later. */
  source: 'seed' | 'custom';
  /** Original seed slug, if `source === 'seed'`. */
  seedId?: string;
  /** Friendly name shown to the user. Defaults to "<Manufacturer> <Model>". */
  displayName: string;
  /** Free-form notes (e.g. "Twin Mercs, prop pitch 19"). */
  notes?: string;
  /** Current fuel level in gallons. Drives FR-025 fuel range. */
  currentFuelGal?: number;
  createdAt: number;
  updatedAt: number;
}
